### ISSUE TITLE
New Tekken Patch 4.1

### ISSUE THREAD

**Issue by JustinHit** [TekkenOverlay/TekkenOverlay#38]
New Tekken update breaks TekkenOverlay, version 4.01.1 is now obsolete.

**Comment by Ardul** [comment]
Same issue.

**Comment by ParkourGrip** [comment]
Since Kulagin disappeared from the face of the earth it will take us game devs that are not good at reverse engineering a long time to update all the memory addresses so be prepared to wait for a while.

**Comment by compsyguy** [comment]
This would be a good reason to have the code more open source. I thought there was a new way of getting the memory addresses that wouldn't require updating as much...
But there's been some work on getting memory addresses here:
https://github.com/WAZAAAAA0/TekkenBot/issues/1
and here:
https://github.com/Kiloutre/TekkenMovesetExtractor/releases/tag/v1.0.32.3

**Comment by ParkourGrip** [comment]
The memory addresses can be modified without the source code by editing `memory-addresses.yaml`. There is also a extensive "Game Memory" section in the settings UI showing the current values that are being red by the program, multilevel pointers (pointer trails) and absolute pointers for every memory value. Open sourcing the project is irrelevant when it comes to finding the addresses.

**Comment by ParkourGrip** [comment]
I have already fixed a the location and size of what we call `frame history` and TBP calls `rollback frames`.
![image](https://user-images.githubusercontent.com/1338621/112071047-53e3c980-8b6f-11eb-9987-9c0f6c6d8828.png)
![image](https://user-images.githubusercontent.com/1338621/112071080-6cec7a80-8b6f-11eb-9a71-d872b136a5e0.png)
Now there have been a lot of changes inside player struct itself, I did not have time to figure them out.
The pointer to the `depthBuffer ` has been moved to a different address. Jack can find that one with a GPU debugger.
The only thing that's left after all of that is `pingStruct`. 
I'm not sure if that's even broken since i did not have time to test anything online.
If the `pingStruct` is invalid only the ping functionality will stop working.
`displayMode` is not used anywhere in the program and the program should work perfectly fine without it.

**Comment by compsyguy** [comment]
That's great the memory addresses can be updated without having access to the source code, but what happens if they make a bigger change that just updating the addresses doesn't fix it? I know we had to make some actual code changes to TBP after one update. 
Also, without knowing what the memory addresses are supposed to be pointing to, it makes it difficult to actually find new ones. 
Like what does 'depthBuffer' supposed to point to?

**Comment by ParkourGrip** [comment]
It's a pointer to the depth buffer texture. The underlining C++ type is `ID3D11Texture2D*` (DirectX11 texture). It's when drawing 3D stuff to know whats in-front and whats behind. GPU debuggers like NVIDIA Nsight can be used to find absolute memory addresses of all currently loaded textures. After that cheat engine can be used to find the pointer trail. Jack knows how to do all of that and he will probably do it when he finds time.

**Comment by JackMcCallum** [comment]
We'll be updating it soon.

**Comment by FimoX** [comment]
Still some errors with that fix ?
https://github.com/WAZAAAAA0/TekkenBot/issues/1#issuecomment-804655359

**Comment by TueurDeBrioche** [comment]
> We'll be updating it soon.

waiting for that <3

**Comment by FimoX** [comment]
Maybe should we stop to use TekkenBot ? How works this new tool ?
https://twitter.com/Harada_TEKKEN/status/1374695816263213059

**Comment by JustinHit** [comment]
Noticed from your post, FimoX that @SergKulaGGin just tweeted the first time this year.

**Comment by ParkourGrip** [comment]
From what i see they encrypted 2 memory values. Both are enumerations. One is for attack type (high/mid/low) one is for correct throw brake. The thing is that since they are using the same encryption key for every instance of Tekken process bypassing that encryption is trivial. All that's necessary is just to change the enumeration values to the new encrypted values. This is defiantly not going to stop people from using auto throw brake / low parry scripts.

**Comment by FimoX** [comment]
@ParkourGrip 
Do you have the new values online for attack_type and throw_tech ?

**Comment by hhm-h** [comment]
Dear developers, when will the updated version be released?
I'm sorry to ask you a question in the middle of my busy schedule. Thank you

**Comment by ParkourGrip** [comment]
Most probably around Monday. No guarantees. I repeat. No guarantees.

**Comment by Nick-bytee** [comment]
Waiting eagerly for update.

**Comment by FimoX** [comment]
@ParkourGrip 
attack_type and throw_tech:
1 - Take the last byte, not 4 bytes
2 - throw_tech can take now 4 values:
https://github.com/WAZAAAAA0/TekkenBot/issues/1

**Comment by ParkourGrip** [comment]
Version [4.10.1](https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.10.1) is out.

**Comment by garryfoe** [comment]
How much for normal version?

**Comment by pimment69** [comment]
@ParkourGrip is it possible to not see the [ overlay ] in our steam name when we play please ?

**Comment by ParkourGrip** [comment]
Nope.

**Comment by pimment69** [comment]
@ParkourGrip why ? :o i have a long name it's not cool haha

**Comment by ParkourGrip** [comment]
Because your opponents deserve to know what they are playing against.

**Comment by pimment69** [comment]
such a great man with lot of respect ! :)
